name: Format Code

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bunx prettier --check './src/**/*.{html,js,ts,svelte,css}'

      - name: Comment on PR if formatting issues found
        if: failure()
        run: |
          echo "::warning ::Formatting issues found. Please run 'bun run format' locally to fix them."
